### ISSUE TITLE
Help to use this fix

### ISSUE THREAD

**Issue by wes1993** [crd/jukebox#1]
Hello, thanks a lot for your work.
how can i use this lambda?
Thanks a lot
Stefano

**Comment by crd** [comment]
Hi @wes1993 -- out of respect for the original author I'm hesitant to give explicit step-by-step instructions. This lambda is installed and executed the same way other AWS Alexa Skill lambdas are used. 

If you have trouble, check CloudWatch Logs -- error messages are pretty decent.

You will need a YouTube `DEVELOPER_KEY` set as an environment variable.
